### ISSUE TITLE
Incorrect Odometry calculation

### ISSUE THREAD

**Issue by fiorano10** [UMLRoverHawks/phidgets#1]
The math for odometry calculation is wrong, so it provides incorrect odometry.

**Comment by nuclearmistake** [comment]
This project is not maintained. That file was not modified since it was imported without history. Maybe the latest phidget ros driver has corrected the math you're finding error in.

**Comment by fiorano10** [comment]
The new Phidget driver doesn't support Wheel encoders yet, this is the only one which I could use. I fixed the odometry math in the commit.
